### ISSUE TITLE
KubeJS failing on first run

### ISSUE THREAD

**Issue by aszecsei** [RCXcrafter/EmbersRekindled#14]
When starting up the game, KubeJS runs into a null pointer exception ([stacktrace](https://mclo.gs/1SuGDvs)) in the `StampingRecipe.getResultItem` function.

Running a `/reload` command causes things to work properly.

Using:
Embers Rekindled 1.20.1-1.1.0
NeoForge 47.1.84
KubeJS 2001.6.4-build.114

**Comment by RCXcrafter** [comment]
If this is happening before a world is loaded then kubejs is trying to get the result of a recipe before tags are loaded, I can handle that a little more gracefully to prevent the log from being spammed but it still won't work properly.

**Comment by TalonsOfStealth** [comment]
I have 100 some odd mods loaded, but after reloading the world all embers machine recipes disappear from JEI, however they still function, I don't know if that will help track down the bug or not

**Comment by Druivenpasta** [comment]
You should be able to lower the priority from kube recipes and make kube load all the tags first, in theory that should fix it
