### ISSUE TITLE
[Suggestion] Re-add Gear Stamp

### ISSUE THREAD

**Issue by Gronglegrowth** [RCXcrafter/EmbersRekindled#17]
In 1.12.2, Embers had a gear stamp, to allow making gears in the stamper. This stamp doesn't exist in the 1.20.1 version. It would be nice to have it again, I think.

**Comment by ianlavr** [comment]
well im pretty sure the gear stamp in 1.12 existed due to Mystical Mechanics

mystical mechanics doesnt exist and without it embers doesnt really use gears
maybe it could be off by default idk

**Comment by RCXcrafter** [comment]
My plan was to leave out the gear stamp until I had a use for it in the main mod but I could port it now if you think it would be useful.
While I'm at it, are there any other stamps that you think would be useful for mod compatibility like rods maybe? I can only think of one mod that uses rods though.

**Comment by Druivenpasta** [comment]
If you ask me add pretty much every shape as a library for pack devs, simply hide them when unused.

**Comment by RCXcrafter** [comment]
Unfortunately hiding them is not really possible in a reliable way, so I won't bother with that. But I can disable their recipes automatically.
I'd prefer to only add a stamp for something if at least two mods use that shape.

**Comment by RCXcrafter** [comment]
I'm closing this issue since the original suggestion has been added but feel free to continue discussing suggestions for other stamps here.
