### ISSUE TITLE
A bin placed beneath stamper disallow changing stamps.

### ISSUE THREAD

**Issue by Anifelus** [RCXcrafter/EmbersRekindled#18]
Exactly what the title says. Kind of inconvenient break the bin every time you need to change stamp.

**Comment by RCXcrafter** [comment]
You're not supposed to put a bin directly under the stamper, if you put the bin under the stamp base it will automatically put all outputs into the bin.

**Comment by Anifelus** [comment]
W what? I was so stupid all that time! My worldview just broke right now because i really used it like that back in 1.12.2... Thx a lot.
