### ISSUE TITLE
Archaic brick recipe bug(?) 

### ISSUE THREAD

**Issue by Anifelus** [RCXcrafter/EmbersRekindled#19]
When you try to craft archaic bricks with more than 1 archaic brick on exchange table the result is not added to the total number of bricks on exchange table. 

To recreate it follow this steps:
   1. Try to craft archaic bricks. At the end of process there will be 5 bricks on the table.
   2. Do not take the result and start crafting process again.
   3. At the end there will be the same amount of bricks. Another ingridients was consumed as usual.

**Comment by RCXcrafter** [comment]
Fixed in version 1.2.0
