### ISSUE TITLE
crafting recipes that use the tinker's hammer consume the hammer if crafted

### ISSUE THREAD

**Issue by kuba26038** [RCXcrafter/EmbersRekindled#2]
pretty much what it sounds like. i assume this isn't supposed to happen and i should report this here

**Comment by kuba26038** [comment]
another issue i found: ember crystals can be crafted into 9 ember shards, but only 6 ember shards are needed to craft an ember crystal

**Comment by RCXcrafter** [comment]
Yeah that was not supposed to happen, both issues are fixed now.
