### ISSUE TITLE
Bins create shadow items

### ISSUE THREAD

**Issue by JoshieGemFinder** [RCXcrafter/EmbersRekindled#21]
With /fill, bins can pick up the same item and show and hold them in each bin at the same time.

If you interact with one of the items in any normal way, any shadow items of it will vanish (however, this is just what happens with shadow items normally in vanilla).

**Comment by RCXcrafter** [comment]
I'm not exactly sure what you mean. As I understand it the /fill command can only place/remove blocks, I don't see what this has to do with items and picking them up.

**Comment by JoshieGemFinder** [comment]
Apologies, I wasn't very clear with my wording.
When two or more bins are on the same "cycle" (as I understand it), they seem to create these false "shadow" items.

**Comment by JoshieGemFinder** [comment]
Apologies again, I have just realized that this is the 1.20.1 repository too (I falsely assumed it was the 1.12 one since it's the one linked on the curseforge and 1.20.1 is still in beta, neglecting to check the repo's about)  
The bug I'm reporting here doesn't exist in the 1.20.1 version, so I'll simply close this issue.

Sorry for wasting your time
