### ISSUE TITLE
item dials not displaying create vault items

### ISSUE THREAD

**Issue by Sculktron123** [RCXcrafter/EmbersRekindled#22]
So i try to use item dials on create mod vaults to see the items inside but when i fill all spaces in the vault with spruce planks the dial still display all slots as NONE. Is this a bug or did i miss something

**Comment by RCXcrafter** [comment]
Fixed in version 1.3.2. Sorry for taking a bit long with this one, I had to rework the dials to make this work but they should work with more stuff from other mods now.
