### ISSUE TITLE
Fluid tags don't include flowing variants of the fluids

### ISSUE THREAD

**Issue by VoidLeech** [RCXcrafter/EmbersRekindled#23]
Vanilla's water and lava tags include the flowing state of the fluid, not just the source. Embers doesn't. 
Could be a design decision of course, but if someone were to build something that triggered based on presence of a certain fluid, only the source blocks would trigger it, which seems undesired, especially with the fact most of the fluids are added to Forge tags and not specifically Embers tags.

**Comment by RCXcrafter** [comment]
Added in version 1.2.0
