### ISSUE TITLE
[Suggestion] Zinc Crystal Seed and Molten Zinc

### ISSUE THREAD

**Issue by Roonas** [RCXcrafter/EmbersRekindled#24]
Addition of a zinc crystal seed and molten zinc for built-in Create compatibility.

**Comment by soleilan** [comment]
What about brass compat for the mixer?

**Comment by RCXcrafter** [comment]
Melting/stamping zinc and brass alloying will be in the next update.

**Comment by RCXcrafter** [comment]
Added in version 1.2.0
