### ISSUE TITLE
Ancient ruins spawn in the middle of the ocean

### ISSUE THREAD

**Issue by TheFlame52** [RCXcrafter/EmbersRekindled#26]
If an instance has both Embers and a mod that lowers terrain height like Tectonic, the ancient ruins will spawn floating in the middle of the ocean. Not a huge problem, but it looks kind of ugly. It could be fixed if a config option was added for the max height of the ruins. That would be pretty RAD of you. ;)

**Comment by RCXcrafter** [comment]
you can use a datapack to change the max height that the ruins generate at, you just have to change [this value](https://github.com/RCXcrafter/EmbersRekindled/blob/rekindled/src/generated/resources/data/embers/worldgen/structure/small_ruin.json#L41).
Though I just had an idea that would allow the ruins to always spawn lower than the bottom of the ocean even if a mod changes it, so I guess that will be in the next update.

**Comment by TheFlame52** [comment]
Thanks!

**Comment by RCXcrafter** [comment]
In version 1.2.0 the small ruins now spawn relative to the bottom of the ocean which should work even if another mod has a biome with a lower ocean floor.
