### ISSUE TITLE
Fails to load on dedicated server neoforge 1.20.1

### ISSUE THREAD

**Issue by PopLamina** [RCXcrafter/EmbersRekindled#32]
Server fails to start with embersrekindled-1.20.1-1.2.0 installed giving the following error:
java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER

**Comment by RCXcrafter** [comment]
Fixed in version 1.2.1
