### ISSUE TITLE
Game crash from using blasting core augment

### ISSUE THREAD

**Issue by Ciberuss2253** [RCXcrafter/EmbersRekindled#33]
I have a blasting core on an weapon. If i hit a zombie and baby zombie at the same time I get this crash.  Seems that this can happen with hitting multiple mobs too. 
[crash-2024-04-15_17.09.18-server.txt](https://github.com/RCXcrafter/EmbersRekindled/files/14984734/crash-2024-04-15_17.09.18-server.txt)

**Comment by RCXcrafter** [comment]
Fixed in version 1.2.2
