### ISSUE TITLE
Ability to control ember deposits in the world

### ISSUE THREAD

**Issue by slava110** [RCXcrafter/EmbersRekindled#35]
Hi. Would be cool to be able to control if certain dimension/biome contains ember. For example, if modpack maker wants to disable ember on the moon. Or maybe even control how much ember certain biome/dimension could contain

**Comment by RCXcrafter** [comment]
This can already be achieved with custom ember bore recipes, custom recipes can just be loaded from a datapack and existing recipes can be removed with a datapack.
https://github.com/RCXcrafter/EmbersRekindled/wiki/Recipes#ember-boring
