### ISSUE TITLE
Death messages from beam deaths do not display correctly.

### ISSUE THREAD

**Issue by Twisted-Code** [RCXcrafter/EmbersRekindled#36]
It looks like it was supposed to interpolate the player name and cause but failed.
![image](https://github.com/RCXcrafter/EmbersRekindled/assets/7110033/b952e249-d0b3-459a-a577-60629a5a6c47)

**Comment by Twisted-Code** [comment]
Relevant localization key: https://github.com/RCXcrafter/EmbersRekindled/blob/rekindled/src/generated/resources/assets/embers/lang/en_us.json#L173
I noticed that the other keys do not have %1 part. I'm not super familiar with Java string interpolation or how Minecraft localization keys are processed, is there a reason you need to specify the parameter index? Or did you mean to replace one with the other and instead you appended? 
In the latter case, I think this is simple enough I can propose a PR to close it promptly; if I'm wrong, you can just reject the PR, no hard feelings.

**Comment by RCXcrafter** [comment]
I'm not sure why this isn't working for you, I use the same formatting codes as all the vanilla death messages and it works just fine for me. Do vanilla death messages work for you? Maybe you have some other mod interfering with death messages.

**Comment by RCXcrafter** [comment]
I figured out why this was happening, it wasn't clear to me at first that this only happend when you die from the beam cannon.
