### ISSUE TITLE
Don't broadcast messages.

### ISSUE THREAD

**Issue by Raycoms** [RCXcrafter/EmbersRekindled#38]
https://github.com/RCXcrafter/EmbersRekindled/blob/rekindled/src/main/java/com/rekindled/embers/blockentity/FluidPipeBlockEntityBase.java#L291

A bunch of the blocks got broadcast mechanics. This causes a lot of network lag on servers. These messages should only be sent to closeby players

**Comment by Raycoms** [comment]
On that note, why are you not using normal blockentity client sync for this?

**Comment by RCXcrafter** [comment]
Yeah this was brought to my attention a few days ago, I'm currently working on fixing it.

**Comment by RCXcrafter** [comment]
It should be good now in version 1.3.2
