### ISSUE TITLE
Working pipe texture broken only after reload chunk

### ISSUE THREAD

**Issue by LunarFactory** [RCXcrafter/EmbersRekindled#39]
![image](https://github.com/RCXcrafter/EmbersRekindled/assets/69113888/09c9aa10-9aff-47ed-8253-177d93d891f4)
This sometimes happen, break pipe and place it again, its texture become normal.
it work normal, only texture happen.

**Comment by LunarFactory** [comment]
I forgot to put my log, sorry.
[latest.log](https://github.com/user-attachments/files/16043321/latest.log)

**Comment by PixVoxel** [comment]
it was chunk-loading mod issue only for server.

**Comment by LunarFactory** [comment]
After check, this only happen for client, to working pipe.

**Comment by RCXcrafter** [comment]
version 1.3.6 should hopefully fix this, let me know if it does or doesn't

**Comment by LunarFactory** [comment]
> version 1.3.6 should hopefully fix this, let me know if it does or doesn't

1.3.6 has a problem on server

Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[latest.log](https://github.com/user-attachments/files/16051651/latest.log)

**Comment by RCXcrafter** [comment]
okay version 1.3.7 fixes the server crash

**Comment by LunarFactory** [comment]
> okay version 1.3.7 fixes the server crash

all the things work well. thanks!
