### ISSUE TITLE
Crystal cell crystal invisible with shaders enabled.

### ISSUE THREAD

**Issue by Hastagaspatcho** [RCXcrafter/EmbersRekindled#47]
Simple as that the crystal is invisible only with shaders enabled
using a Minecraft 1.20.1 install with just:
NeoForge 47.1.106
Embers Rekindled 1.20.1-1.3.9
Oculus 1.7.0
Embeddium 0.3.31+MC1.20.1
Embeddium++ 1.2.13
JEI 15.18.0.79
and complementary reimagined 5.2.2
Screenshots included as well.
![2024-09-10_19 06 02](https://github.com/user-attachments/assets/6d563902-9927-4197-a4c3-0ffc431b24c7)
![2024-09-10_19 06 08](https://github.com/user-attachments/assets/7d0c4b7f-8b5c-4d11-8bfd-d07c80e00384)

**Comment by Sirplop** [comment]
you can change the renderer to the fallback renderer in the embers-client config file - doing so should improve shader compatibility

**Comment by Hastagaspatcho** [comment]
That did the trick, thanks for the quick response.
Field chart still looks a little funky but its usable now and that's what matters
![2024-09-10_19 41 22](https://github.com/user-attachments/assets/b54f08dd-877d-4e99-9853-1ea13fa81879)

**Comment by RCXcrafter** [comment]
What is oculus doing to my quads 💀
