### ISSUE TITLE
Feature Request: Config Option for Metal Seeds Recipe

### ISSUE THREAD

**Issue by toErIpNid** [RCXcrafter/EmbersRekindled#5]
Glad to see this being ported to newer versions, but I really don't like the change that metal seeds must be found in loot. I love Embers primarily because you don't need to grind much of anything just to use the mod's features, and forcing players to go out and find them in loot kinda goes against that. They weren't very powerful to begin with unless you had _a lot_ of time on your hands, so I don't really think they deserve this nerf personally.

**Comment by RCXcrafter** [comment]
I won't add a config for that but you can use a datapack to add custom alchemy recipesas well as recipes for all the other machines.
