### ISSUE TITLE
(1.20.1) Pipe models are incompatible with ModernFix's Dynamic Resources

### ISSUE THREAD

**Issue by mosharky** [RCXcrafter/EmbersRekindled#6]
[Log with relevant error](https://mclo.gs/vAcci5N#L1465)
[Crash report](https://mclo.gs/3BhBC9r) (this crash isn't consistent - not really sure what's going on here)

Dynamic Resources is a config option for [ModernFix](https://www.curseforge.com/minecraft/mc-mods/modernfix) that significantly reduces ram usage. It's incompatible with baked models, which seems to be what Embers uses for pipe models.

I'm not able to reproduce the crash and resource fail at all with only Embers and ModernFix, but the pipe model is definitely not rendering properly at the very least.

**Comment by mosharky** [comment]
The crash report was from The Aether or one of its addons. [Here's the proper crash](https://mclo.gs/2apEAzh) (with the same error as in the log I linked earlier). Again though, it's not crashing with just ModernFix + Dynamic Resources and Embers, so I'm not sure what's going on here. I'm gonna do a binary search and will report back.

**Comment by mosharky** [comment]
Okay, so it's a three-way crash between Cobblemon, ModernFix + dynamic resources, and Embers.

[*actual* proper crash report](https://mclo.gs/Wab4URp)
[*actual* proper log](https://mclo.gs/7uibZnp)

I do believe that once the pipe model isn't using a baked model, then the crash shouldn't occur. It's very odd that Cobblemon is the reason it actually crashes though.

**Comment by RCXcrafter** [comment]
I won't fix this right away since it only happens when enabling a config option in a performance mod that modifies vanilla behavior but I will fix this eventually, it'll require me to rewrite the way I load my pipe models.

**Comment by mosharky** [comment]
no worries, I totally get it! That option is such a big deal because of its gains though. It's easily over 50% less ram usage.

If you had to "rank" it on a list of priorities, where would it go?

**Comment by RCXcrafter** [comment]
I don't really have a clear list of priorities, I don't know where I would put this one among the other things I want to do.

**Comment by mosharky** [comment]
Fair enough, thanks anyways!

**Comment by mosharky** [comment]
ModernFix has now blacklisted Embers from its model stuff https://github.com/embeddedt/ModernFix/issues/284
