### ISSUE TITLE
Repeated NPE crashes for ItemPipe

### ISSUE THREAD

**Issue by djnifos** [RCXcrafter/EmbersRekindled#9]
[https://mclo.gs/ojsCKtq](https://mclo.gs/ojsCKtq)
[https://paste.ee/p/h6yUT](https://paste.ee/p/h6yUT)

Same user, only one we've seen.  In ATM9.  Forge 47.1.3  Mod Version 1.0.2

**Comment by RCXcrafter** [comment]
I've seen this issue a couple of times now. I've been thinking about rewriting the way my pipe models are loaded which should fix this so I guess I'll do that sooner rather than later.

**Comment by RCXcrafter** [comment]
This should be fixed in version 1.0.3, let me know if it isn't.
